### ISSUE TITLE
More Challenges

### ISSUE THREAD

**Issue by ghost** [majid-darvishfard/python-learning#1]
# Challenge
here we have some challenges to add to your shopping list code.

1. CRUD
     1. already you write the Create and read methods.
     1. please write edit function into your shopping list.
          * for example, the user selects an item, then he/she update that specific item.
      1. the last functionality of this issue is creating the remove method. the user selects a specific item and request he/she wants to remove that item. finally, you ask "are you sure to removing {} item?" if the user writes yes, you remove the item else you get back onto the shopping list.

**NOTE:** dear Majid, at first please fix your previous code. Then write a report when a user added an item. for example, he added an apple and you write this sentence: ' you added {item} into your list. Now you have {count_of_list} items.'.

If you complete this issue, you can get a new challenge.

Good luck

**Comment by majid-darvishfard** [comment]
complete
plz check

**Comment by ghost** [comment]
I don't see any update on shopping list repository with CRUD feature...

**Comment by majid-darvishfard** [comment]
add  CRUD to shopping lists
