### ISSUE TITLE
modular

### ISSUE THREAD

**Issue by ghost** [majid-darvishfard/python-learning#4]
# Modular programming

please, refactor your codes with a function.

**Comment by majid-darvishfard** [comment]
Plz check

**Comment by ghost** [comment]
read #5 then fix your codes again.

Why you delete your previous repositories?
Do you know how can you update your codes? If you don't know it, i can help you. just tell me.

**Comment by majid-darvishfard** [comment]
I push 2 file with git push  command with -- force option 
,I think must firs pull repository from GitHub then change current local repo then push that ?!

How add new project file to current  GitHub repository from git command ?!

**Comment by majid-darvishfard** [comment]
Is need create separate repository for project !!??

**Comment by ghost** [comment]
Your question depends on your action. So, if you create a repository in GitHub and in the processing of doing that, you shouldn't add any file like readme.md or changelog.md and other files like them.  if you did that, you must first send a pull request, then push it.

If you didn't do that, at first you can push your codes.

got it?

**Comment by ghost** [comment]
To adding more project these are your steps:

> status used to see the steps.

```
git status
git add .
git status
git commit -m "message"
git status
git push
```

**Comment by ghost** [comment]
These lines could be placed in a function.

https://github.com/majid-darvishfard/python-learning/blob/bd6149cbe1d3210e58b63ba6617d6af8b8a4ab12/dragon.py#L48

https://github.com/majid-darvishfard/python-learning/blob/bd6149cbe1d3210e58b63ba6617d6af8b8a4ab12/dragon.py#L59

The rest of the code is nice.
well done.

#1 
#### Do you want more challenges?
if you want, which one do you take:

- [x] shopping list

- [x] dungeon and dragon

**Comment by majid-darvishfard** [comment]
از چالش بیشتر استقبال میشود 
فرقی نمیکنه کدوم پروژه باشه

میخواید از برای هر دو تاش بگید آخر هفته انجام بدم

**Comment by majid-darvishfard** [comment]
از چالش بیشتر استقبال میشود 
فرقی نمیکنه کدوم پروژه باشه

میخواید از برای هر دو تاش بگید آخر هفته انجام بدم

**Comment by majid-darvishfard** [comment]
از چالش بیشتر استقبال میشود 
فرقی نمیکنه کدوم پروژه باشه

میخواید از برای هر دو تاش بگید آخر هفته انجام بدم

**Comment by majid-darvishfard** [comment]
از چالش بیشتر استقبال میشود 
فرقی نمیکنه کدوم پروژه باشه

میخواید از برای هر دو تاش بگید آخر هفته انجام بدم

**Comment by ghost** [comment]
بسیار عالی، به روی چشم
