### ISSUE TITLE
Bad Practice

### ISSUE THREAD

**Issue by ghost** [majid-darvishfard/python-learning#5]
#4 
# Keys To A Good Function

[Single responsibility](https://en.wikipedia.org/wiki/Single_responsibility_principle)
> A function should have a single responsibility. That is, it should do one thing and only one thing. One great reason is that if every function only does one thing, there is only one reason ever to change it: if the way in which it does that thing must change. It also becomes clear when a function can be deleted: if, when making changes elsewhere, it becomes clear the function's single responsibility is no longer needed, simply remove it.

[REFERENCE](https://jeffknupp.com/blog/2018/10/11/write-better-python-functions/)

## Best practices

* Is sensibly named
* Has a single responsibility
* Includes a docstring
* Returns a value
* Is not longer than 50 lines
* Is idempotent and, if possible, pure

## Bad practice

You must not use global variables. You can know more about it in this [link](https://stackoverflow.com/questions/19158339/why-are-global-variables-evil)

https://github.com/majid-darvishfard/python-learning/blob/fd376b54210e0b0e97cf54c5c2ee7964d64a4b0d/letter_geuss.py#L19

**Comment by majid-darvishfard** [comment]
تشکر بابت توضیحاتتون
الان به نظرتون کدوم بخش رو باید به صورت تابع نوشت

**Comment by ghost** [comment]
اول از همه اینکه داخل توابع متغیر های عمومی تعریف نکن.
اصلا خوب نیست و درست هم نیست. دلیلش رو داخل لینکی که گداشتم می توانید مشاهده کنید.

هر تابع دقیقا یک کار باید انجام دهد که گفته شده هر تابع باید Single responsibility داشته باشد.
توضیحات این موضوع نیز در لینکی قرار داده شده است.

اشکالاتی که در حال حاضر به شما وارد هست، به این خاطر هست که کد نویس بهتری در جامعه برنامه نویسان باشید وگرنه همه کدها اجرا می شوند و یک خروجی را نمایش می دهند.

به عنوان مثال تابع Again شما در حال حاضر دو کار انجام می دهد.
در صورتی که تابع نوشته شده را می توانید یک تابع دیگر با نام clear تعریف کنید.
تا وظیفه پاک کردن صفحه را تنها داشته باشد.

**Comment by majid-darvishfard** [comment]
سعی میشود موارد ذکر شده را از این به بعد رعایت نمایم
