### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [majid-darvishfard/python-learning#6]
why x - 1 +1 ?

https://github.com/majid-darvishfard/python-learning/blob/bd6149cbe1d3210e58b63ba6617d6af8b8a4ab12/dragon.py#L24

**Comment by majid-darvishfard** [comment]
منطق این کارم این بودش:
چون وقتی که میخوایم عنصر مورد نظر رو درج کنیم 
 ، ایندکس  در جدول از صفر شروع میشه  برای همین از ایندکس عنصر  مورد نظر   یکی  کم میکنیم و چون نمی‌خوایم در سطر اول درج بشه. یکی بهش اضافه کردم
