### ISSUE TITLE
creative minded

### ISSUE THREAD

**Issue by ghost** [majid-darvishfard/python-learning#7]
**Congratulation, you passed two challenges in a day.**
#2

> You are so good. Keep going

Here we have some new challenges:

- [x]   items can have a category.

     - For example, orange and apple are items of a citrus category. Then, milk and sugar are items of supermarket category.

- [x]   You need to show items of a category.

- [x]   You can implement Update and Delete options for the category.

**Tips:**

1. You can define items globally at the first line of your program. The benefit is that you don't need to send an argument like items into your functions.

1. If I enter a number, in the other words you have to accept just alphabet and ignore any number when the user is answering to your program.

1. How do you manage if the user says how much milk he/she wants?

1. You need to show the list within a for the loop. Not just showing the list. it is not user-friendly.

#1
append_list --> add_item
edit --> edit_item

**Comment by majid-darvishfard** [comment]
- add item category  and item count to shooping_list.
- get item name, item count and item getegory  from the user in first time if item exist only add items Count , and  dont ask again item  category from user 
- allow update item property (name-count-category)
- ask question befor save,update,remove items
